### ISSUE TITLE
[Suggestion] Reopen tickets by UUID, use webhooks to resend chat history (maybe to a max of 20 messages)

### ISSUE THREAD

**Issue by burturt** [Scarsz/DiscordSupportBot-Legacy#16]
Title says it all: Reopen tickets by UUID and use webhooks to imitate the last of the conversation. Obviously fairly hard to do but it's a suggestion.

**Comment by Scarsz** [comment]
Definitely won't be done. I have plans for the transcript output to eventually be an imitated Discord channel which should be close enough.

**Comment by Andre601** [comment]
I like the idea of that discord thing and already saw a bot, that did a similar thing for chat-history.,, It was nice.
